dnd-bot/dnd_bot/dc/init.py

dc: init.py: add discord status - listening to /help

---

dnd-bot/dnd_bot/dc/ui/messager.py

Message deletion

---

dnd-bot/dnd_bot/dc/cogs/command_shutdown.py

Bot shutdown command

---

dnd-bot/dnd_bot/dc/ui/views/view_movement.py

views: view_movement.py: rearrange arrows to resemble real life arrows

---

dnd-bot/dnd_bot/database/database_connection.py

database: database_connection.py: handle sensitive information, closes #71

---

README.md

README.md: add codeql status badge

---

dnd-bot/dnd_bot/logic/utils/utils.py

Generating circle points for given radius

---

dnd-bot/dnd_bot/dc/cogs/command_latency.py

cogs: command_latency.py: add command to debug bot latency

---

.gitignore
dnd-bot/dnd_bot/logic/utils/utils.py

assets: change temporary images location

---

dnd-bot/dnd_bot/dc/ui/views/view_game.py

dc: ui: views: view_game.py: fix cancel buttons in character submenus

---

dnd-bot/dnd_bot/dc/ui/message_templates.py
dnd-bot/dnd_bot/dc/ui/messager.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/dc/ui/views/view_lobby.py
dnd-bot/dnd_bot/dc/utils/utils.py

Player turn embed

---

dnd-bot/dnd_bot/logic/prototype/game.py

add creatures_queue assignment from parameter if is not None

---

dnd-bot/dnd_bot/dc/ui/message_templates.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/dc/ui/views/view_lobby.py

changed map_view_message to turn_view_message

---

dnd-bot/dnd_bot/dc/init.py
dnd-bot/dnd_bot/dc/ui/messager.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/dc/ui/views/view_lobby.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/prototype/entity.py
dnd-bot/dnd_bot/logic/prototype/game.py
dnd-bot/dnd_bot/logic/utils/utils.py
dnd-bot/requirements.txt

Minor corrections

---

dnd-bot/dnd_bot/dc/ui/views/view_game.py

Refactor game views for better code quality and parallelism

---

dnd-bot/dnd_bot/dc/cogs/command_shutdown.py
dnd-bot/dnd_bot/dc/ui/message_templates.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/dc/ui/views/view_lobby.py
dnd-bot/dnd_bot/logic/game/game_loop.py
dnd-bot/dnd_bot/logic/game/handler_game.py
dnd-bot/dnd_bot/logic/game/handler_movement.py
dnd-bot/dnd_bot/logic/lobby/handler_start.py
dnd-bot/dnd_bot/logic/prototype/game.py

Game loop refactor

---

dnd-bot/dnd_bot/logic/lobby/handler_create.py
dnd-bot/dnd_bot/logic/prototype/multiverse.py
dnd-bot/dnd_bot/logic/utils/utils.py

Render  optimization

---

dnd-bot/dnd_bot/logic/utils/utils.py

fixed circle generation (temporary)

---

docker-compose.yml

check if docker-compose works correctly

---

dnd-bot/dnd_bot/logic/prototype/creature.py
dnd-bot/dnd_bot/logic/prototype/entity.py
dnd-bot/dnd_bot/logic/prototype/event.py
dnd-bot/dnd_bot/logic/prototype/game.py
dnd-bot/dnd_bot/logic/prototype/item.py
dnd-bot/dnd_bot/logic/prototype/player.py
dnd-bot/dnd_bot/logic/prototype/skill.py
dnd-bot/dnd_bot/logic/prototype/user.py

Creating database prototype

---

dnd-bot/dnd_bot/dc/ui/messager.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/logic/game/game_loop.py
dnd-bot/dnd_bot/logic/game/handler_game.py
dnd-bot/dnd_bot/logic/prototype/game.py

 Reset of view for non active player when active player does action fix

---

dnd-bot/dnd_bot/database/database_connection.py
dnd-bot/dnd_bot/database/database_creature.py
dnd-bot/dnd_bot/database/database_entity.py
dnd-bot/dnd_bot/database/database_game.py
dnd-bot/dnd_bot/database/database_player.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/prototype/database_object.py
dnd-bot/dnd_bot/logic/prototype/entity.py
dnd-bot/dnd_bot/logic/prototype/multiverse.py
dnd-bot/dnd_bot/logic/prototype/player.py
dnd-bot/dnd_bot/tests/autoconf.py
dnd-bot/dnd_bot/tests/create_tables.sql
dnd-bot/dnd_bot/tests/populate_tables.sql
dnd-bot/dnd_bot/tests/test_game.py
dnd-bot/dnd_bot/tests/test_player.py

Saving state to db silentsky

---

dnd-bot/dnd_bot/dc/ui/message_templates.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/logic/game/handler_game.py

ui: fix checking stats when a creature is performing actions

---

dnd-bot/dnd_bot/dc/cogs/command_start.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/lobby/handler_start.py

add starting game in developer mode

---

dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/prototype/entities/hole.py
dnd-bot/dnd_bot/logic/prototype/entities/mushrooms.py
dnd-bot/dnd_bot/logic/prototype/entities/rock.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_connector.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_corner_in.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_corner_out.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_crossroads.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_pillar_a.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_pillar_b.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_pillar_c.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_straight_a.py
dnd-bot/dnd_bot/logic/prototype/entities/walls/dungeon_straight_b.py

Reworked spawing of entities

---

dnd-bot/dnd_bot/dc/ui/message_templates.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/prototype/equipment.py
dnd-bot/dnd_bot/logic/prototype/items/bow.py
dnd-bot/dnd_bot/logic/prototype/items/staff.py
dnd-bot/dnd_bot/logic/prototype/items/sword.py
dnd-bot/dnd_bot/logic/prototype/player.py

Add some basic item classes and add to player based on class

---

dnd-bot/dnd_bot/dc/ui/message_templates.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/logic/prototype/game.py

added attack view

---

dnd-bot/dnd_bot/tests/populate_tables.sql
dnd-bot/dnd_bot/tests/test_game.py

tests: add more tests to game

---

dnd-bot/dnd_bot/database/database_creature.py
dnd-bot/dnd_bot/database/database_entity.py
dnd-bot/dnd_bot/database/database_player.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/prototype/creature.py
dnd-bot/dnd_bot/logic/prototype/player.py

delete unnecesary attributes

---

dnd-bot/dnd_bot/database/database_game.py
dnd-bot/dnd_bot/database/database_player.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/tests/create_tables.sql
dnd-bot/dnd_bot/tests/test_game.py
dnd-bot/dnd_bot/tests/test_player.py

tests: fix failing tests

---

dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/logic/game/handler_attack.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/prototype/game.py

logic: handler_attack: handle a player attacking a creature

---

dnd-bot/dnd_bot/dc/ui/messager.py
dnd-bot/dnd_bot/dc/ui/views/view_character_creation.py
dnd-bot/dnd_bot/logic/character_creation/handler_alignment.py
dnd-bot/dnd_bot/logic/character_creation/handler_character_creation.py
dnd-bot/dnd_bot/logic/character_creation/handler_class.py
dnd-bot/dnd_bot/logic/character_creation/handler_race.py
dnd-bot/dnd_bot/logic/character_creation/handler_stats_retrospective.py
dnd-bot/dnd_bot/logic/game/game_start.py

Extract logic from views to handlers in character creation

---

dnd-bot/dnd_bot/dc/cogs/command_pause.py
dnd-bot/dnd_bot/dc/cogs/command_resume.py
dnd-bot/dnd_bot/logic/game/handler_game.py

Add pause and resume commands

---

docker-compose.yml

Fixed docker-compose.yml

---

dnd-bot/dnd_bot/assets/campaigns/campaign.json
dnd-bot/dnd_bot/dc/ui/message_templates.py
dnd-bot/dnd_bot/dc/ui/views/view_character_creation.py
dnd-bot/dnd_bot/logic/character_creation/handler_character_creation.py
dnd-bot/dnd_bot/logic/prototype/character_class.py
dnd-bot/dnd_bot/logic/prototype/character_race.py
dnd-bot/dnd_bot/logic/utils/utils.py

Move races and classes to json

---

dnd-bot/dnd_bot/assets/campaigns/campaign.json

change warrior emoji to unicode to avoid conversion bugs

---

dnd-bot/dnd_bot/dc/cogs/command_create.py
dnd-bot/dnd_bot/dc/cogs/command_join.py
dnd-bot/dnd_bot/dc/cogs/command_pause.py
dnd-bot/dnd_bot/dc/cogs/command_resume.py
dnd-bot/dnd_bot/dc/cogs/command_start.py
dnd-bot/dnd_bot/dc/ui/views/view_character_creation.py
dnd-bot/dnd_bot/dc/ui/views/view_lobby.py
dnd-bot/dnd_bot/logic/character_creation/handler_alignment.py
dnd-bot/dnd_bot/logic/character_creation/handler_character_creation.py
dnd-bot/dnd_bot/logic/character_creation/handler_class.py
dnd-bot/dnd_bot/logic/character_creation/handler_race.py
dnd-bot/dnd_bot/logic/character_creation/handler_stats_retrospective.py
dnd-bot/dnd_bot/logic/game/handler_game.py
dnd-bot/dnd_bot/logic/lobby/handler_create.py
dnd-bot/dnd_bot/logic/lobby/handler_join.py
dnd-bot/dnd_bot/logic/lobby/handler_ready.py
dnd-bot/dnd_bot/logic/lobby/handler_start.py
dnd-bot/dnd_bot/logic/utils/exceptions.py

Add custom exceptions and delete error messages that were left out when ending the turn

---

dnd-bot/dnd_bot/assets/campaigns/campaign.json
dnd-bot/dnd_bot/dc/ui/message_templates.py

Rework character creation so the text is shorter in some places

---

dnd-bot/dnd_bot/dc/cogs/command_create.py
dnd-bot/dnd_bot/dc/cogs/command_join.py
dnd-bot/dnd_bot/dc/init.py
dnd-bot/dnd_bot/dc/ui/messager.py
dnd-bot/dnd_bot/dc/ui/views/view_character_creation.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/dc/ui/views/view_lobby.py
dnd-bot/dnd_bot/dc/utils/message_holder.py
dnd-bot/dnd_bot/logic/utils/exceptions.py

Rework discord communication interface to provide simpler error messages

---

.gitignore
dnd-bot/dnd_bot/dc/init.py
dnd-bot/dnd_bot/dc/ui/messager.py
dnd-bot/dnd_bot/dc/ui/views/view_character_creation.py
dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/dc/ui/views/view_lobby.py
dnd-bot/dnd_bot/logic/character_creation/handler_stats_retrospective.py

Add custom handler for all unexpected exceptions

---

dnd-bot/dnd_bot/dc/ui/views/view_game.py
dnd-bot/dnd_bot/logic/game/game_loop.py
dnd-bot/dnd_bot/logic/game/handler_loot_corpse.py
dnd-bot/dnd_bot/logic/prototype/game.py
dnd-bot/dnd_bot/logic/utils/utils.py

Rework of find_position_to_check() Issue#189

---

dnd-bot/dnd_bot/database/database_connection.py
dnd-bot/dnd_bot/database/database_creature.py
dnd-bot/dnd_bot/database/database_entity.py
dnd-bot/dnd_bot/database/database_player.py
dnd-bot/dnd_bot/dc/cogs/command_start.py
dnd-bot/dnd_bot/logic/character_creation/handler_stats_retrospective.py
dnd-bot/dnd_bot/logic/game/game_loop.py
dnd-bot/dnd_bot/logic/game/game_start.py
dnd-bot/dnd_bot/logic/game/handler_movement.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/prototype/item.py
dnd-bot/dnd_bot/tests/test_database_creature.py
dnd-bot/dnd_bot/tests/test_database_entity.py

load entities to db in a parallel manner during world initialization

---

dnd-bot/dnd_bot/logic/prototype/game.py
dnd-bot/dnd_bot/logic/utils/utils.py

Ray tracing

---

dnd-bot/dnd_bot/database/database_creature.py
dnd-bot/dnd_bot/database/database_player.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/tests/create_tables.sql
dnd-bot/dnd_bot/tests/test_database_creature.py
dnd-bot/dnd_bot/tests/test_database_player.py
dnd-bot/dnd_bot/tests/test_database_player_item.py
dnd-bot/dnd_bot/tests/test_player.py

…attributes to creature related database methods

add max_hp and initial_action_points attributes to database Creature calls

---

dnd-bot/dnd_bot/database/database_creature.py
dnd-bot/dnd_bot/database/database_entity.py
dnd-bot/dnd_bot/database/database_game.py
dnd-bot/dnd_bot/database/database_player.py
dnd-bot/dnd_bot/database/database_user.py
dnd-bot/dnd_bot/dc/cogs/command_create.py
dnd-bot/dnd_bot/logic/game/game_loop.py
dnd-bot/dnd_bot/logic/game/handler_game.py
dnd-bot/dnd_bot/logic/game/initialize_world.py
dnd-bot/dnd_bot/logic/lobby/handler_create.py
dnd-bot/dnd_bot/tests/create_tables.sql
dnd-bot/dnd_bot/tests/populate_tables.sql
dnd-bot/dnd_bot/tests/test_database_creature.py
dnd-bot/dnd_bot/tests/test_database_entity.py
dnd-bot/dnd_bot/tests/test_database_game.py
dnd-bot/dnd_bot/tests/test_database_player.py
dnd-bot/dnd_bot/tests/test_database_user.py
dnd-bot/dnd_bot/tests/test_game.py

Adjust code to new db

---

dnd-bot/dnd_bot/dc/cogs/command_start.py

make start command developers only
